In [1]:
import pandas as pd

In [2]:
trans_df = pd.read_excel('transposed_RC.xlsx', sheet_name='Sheet2')

In [3]:
trans_df.head()

,Unnamed: 0,Type,1982-01-01 00:00:00,1982-02-01 00:00:00,1982-03-01 00:00:00,1982-04-01 00:00:00,1982-05-01 00:00:00,1982-06-01 00:00:00,1982-07-01 00:00:00,1982-08-01 00:00:00,...,2019-01-01 00:00:00,2019-02-01 00:00:00,2019-03-01 00:00:00,2019-04-01 00:00:00,2019-05-01 00:00:00,2019-06-01 00:00:00,2019-07-01 00:00:00,2019-08-01 00:00:00,2019-09-01 00:00:00,2019-10-01 00:00:00
0,Austria,L,10.0,10.0,10.0,9.0,9.0,8.0,8.0,8.0,...,1,1,1,1,1,1,1,0,1,1
1,Austria,O,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,Denmark,L,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,Denmark,O,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,0,0,0,0,1,1,1,0,0,0
4,France,L,28.0,28.0,26.0,28.0,28.0,23.0,19.0,19.0,...,2,1,2,2,1,1,3,3,3,1

In [4]:
land_df=trans_df[trans_df['Type']=='L']
land_df=land_df.drop('Type',axis=1)
land_df.set_index(['Unnamed: 0'], inplace=True)
trans_land=land_df.transpose()
headers=trans_land.columns.tolist()
df_list=[]
for column in headers:
    df=trans_land[[column]]
    df['nation']=column
    df.rename(columns={column:'Count'}, inplace=True)
    df_list.append(df)
new_land=pd.concat(df_list)
new_land.reset_index(drop=False, inplace=True)
new_land['Type']="In-Land"
new_land.rename(columns={'index':'Date','nation':'country'},inplace=True)
new_land

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

Unnamed: 0       Date  Count       country     Type
0          1982-01-01   10.0       Austria  In-Land
1          1982-02-01   10.0       Austria  In-Land
2          1982-03-01   10.0       Austria  In-Land
3          1982-04-01    9.0       Austria  In-Land
4          1982-05-01    9.0       Austria  In-Land
5          1982-06-01    8.0       Austria  In-Land
6          1982-07-01    8.0       Austria  In-Land
7          1982-08-01    8.0       Austria  In-Land
8          1982-09-01    8.0       Austria  In-Land
9          1982-10-01    8.0       Austria  In-Land
10         1982-11-01    8.0       Austria  In-Land
11         1982-12-01    8.0       Austria  In-Land
12         1983-01-01   11.0       Austria  In-Land
13         1983-02-01    9.0       Austria  In-Land
14         1983-03-01    9.0       Austria  In-Land
15         1983-04-01   10.0       Austria  In-Land
16         1983-05-01   11.0       Austria  In-Land
17         1983-06-01   10.0       Austria  In-Land
18         1983-07-01    9.0       Austria  In-Land
19         1983-08-01    9.0       Austria  In-Land
20         1983-09-01    9.0       Austria  In-Land
21         1983-10-01    9.0       Austria  In-Land
22         1983-11-01    5.0       Austria  In-Land
23         1983-12-01    5.0       Austria  In-Land
24         1984-01-01    8.0       Austria  In-Land
25         1984-02-01    8.0       Austria  In-Land
26         1984-03-01    6.0       Austria  In-Land
27         1984-04-01    6.0       Austria  In-Land
28         1984-05-01   11.0       Austria  In-Land
29         1984-06-01    8.0       Austria  In-Land
...               ...    ...           ...      ...
31296      2017-05-01    0.0  Oth Far East  In-Land
31297      2017-06-01    0.0  Oth Far East  In-Land
31298      2017-07-01    0.0  Oth Far East  In-Land
31299      2017-08-01    0.0  Oth Far East  In-Land
31300      2017-09-01    0.0  Oth Far East  In-Land
31301      2017-10-01    0.0  Oth Far East  In-Land
31302      2017-11-01    0.0  Oth Far East  In-Land
31303      2017-12-01    0.0  Oth Far East  In-Land
31304      2018-01-01    0.0  Oth Far East  In-Land
31305      2018-02-01    0.0  Oth Far East  In-Land
31306      2018-03-01    0.0  Oth Far East  In-Land
31307      2018-04-01    0.0  Oth Far East  In-Land
31308      2018-05-01    0.0  Oth Far East  In-Land
31309      2018-06-01    0.0  Oth Far East  In-Land
31310      2018-07-01    0.0  Oth Far East  In-Land
31311      2018-08-01    0.0  Oth Far East  In-Land
31312      2018-09-01    0.0  Oth Far East  In-Land
31313      2018-10-01    0.0  Oth Far East  In-Land
31314      2018-11-01    0.0  Oth Far East  In-Land
31315      2018-12-01    0.0  Oth Far East  In-Land
31316      2019-01-01    0.0  Oth Far East  In-Land
31317      2019-02-01    0.0  Oth Far East  In-Land
31318      2019-03-01    0.0  Oth Far East  In-Land
31319      2019-04-01    0.0  Oth Far East  In-Land
31320      2019-05-01    0.0  Oth Far East  In-Land
31321      2019-06-01    0.0  Oth Far East  In-Land
31322      2019-07-01    0.0  Oth Far East  In-Land
31323      2019-08-01    0.0  Oth Far East  In-Land
31324      2019-09-01    0.0  Oth Far East  In-Land
31325      2019-10-01    0.0  Oth Far East  In-Land

[31326 rows x 4 columns]

In [6]:
shore_df=trans_df[trans_df['Type']=='O']
shore_df=shore_df.drop('Type',axis=1)
shore_df.set_index(['Unnamed: 0'], inplace=True)
trans_shore=shore_df.transpose()
headers=trans_shore.columns.tolist()
df_list=[]
for column in headers:
    df=trans_shore[[column]]
    df['nation']=column
    df.rename(columns={column:'Count'}, inplace=True)
    df_list.append(df)
new_shore=pd.concat(df_list)
new_shore.reset_index(drop=False, inplace=True)
new_shore['Type']="Off-Shore"
new_shore.rename(columns={'index':'Date','nation':'country'},inplace=True)
new_shore

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

Unnamed: 0       Date  Count       country       Type
0          1982-01-01    0.0       Austria  Off-Shore
1          1982-02-01    0.0       Austria  Off-Shore
2          1982-03-01    0.0       Austria  Off-Shore
3          1982-04-01    0.0       Austria  Off-Shore
4          1982-05-01    0.0       Austria  Off-Shore
5          1982-06-01    0.0       Austria  Off-Shore
6          1982-07-01    0.0       Austria  Off-Shore
7          1982-08-01    0.0       Austria  Off-Shore
8          1982-09-01    0.0       Austria  Off-Shore
9          1982-10-01    0.0       Austria  Off-Shore
10         1982-11-01    0.0       Austria  Off-Shore
11         1982-12-01    0.0       Austria  Off-Shore
12         1983-01-01    0.0       Austria  Off-Shore
13         1983-02-01    0.0       Austria  Off-Shore
14         1983-03-01    0.0       Austria  Off-Shore
15         1983-04-01    0.0       Austria  Off-Shore
16         1983-05-01    0.0       Austria  Off-Shore
17         1983-06-01    0.0       Austria  Off-Shore
18         1983-07-01    0.0       Austria  Off-Shore
19         1983-08-01    0.0       Austria  Off-Shore
20         1983-09-01    0.0       Austria  Off-Shore
21         1983-10-01    0.0       Austria  Off-Shore
22         1983-11-01    0.0       Austria  Off-Shore
23         1983-12-01    0.0       Austria  Off-Shore
24         1984-01-01    0.0       Austria  Off-Shore
25         1984-02-01    0.0       Austria  Off-Shore
26         1984-03-01    0.0       Austria  Off-Shore
27         1984-04-01    0.0       Austria  Off-Shore
28         1984-05-01    0.0       Austria  Off-Shore
29         1984-06-01    0.0       Austria  Off-Shore
...               ...    ...           ...        ...
31296      2017-05-01    0.0  Oth Far East  Off-Shore
31297      2017-06-01    0.0  Oth Far East  Off-Shore
31298      2017-07-01    0.0  Oth Far East  Off-Shore
31299      2017-08-01    0.0  Oth Far East  Off-Shore
31300      2017-09-01    0.0  Oth Far East  Off-Shore
31301      2017-10-01    0.0  Oth Far East  Off-Shore
31302      2017-11-01    0.0  Oth Far East  Off-Shore
31303      2017-12-01    0.0  Oth Far East  Off-Shore
31304      2018-01-01    0.0  Oth Far East  Off-Shore
31305      2018-02-01    0.0  Oth Far East  Off-Shore
31306      2018-03-01    0.0  Oth Far East  Off-Shore
31307      2018-04-01    0.0  Oth Far East  Off-Shore
31308      2018-05-01    0.0  Oth Far East  Off-Shore
31309      2018-06-01    0.0  Oth Far East  Off-Shore
31310      2018-07-01    0.0  Oth Far East  Off-Shore
31311      2018-08-01    0.0  Oth Far East  Off-Shore
31312      2018-09-01    0.0  Oth Far East  Off-Shore
31313      2018-10-01    0.0  Oth Far East  Off-Shore
31314      2018-11-01    0.0  Oth Far East  Off-Shore
31315      2018-12-01    0.0  Oth Far East  Off-Shore
31316      2019-01-01    0.0  Oth Far East  Off-Shore
31317      2019-02-01    0.0  Oth Far East  Off-Shore
31318      2019-03-01    0.0  Oth Far East  Off-Shore
31319      2019-04-01    0.0  Oth Far East  Off-Shore
31320      2019-05-01    0.0  Oth Far East  Off-Shore
31321      2019-06-01    0.0  Oth Far East  Off-Shore
31322      2019-07-01    0.0  Oth Far East  Off-Shore
31323      2019-08-01    0.0  Oth Far East  Off-Shore
31324      2019-09-01    0.0  Oth Far East  Off-Shore
31325      2019-10-01    0.0  Oth Far East  Off-Shore

[31326 rows x 4 columns]

In [9]:
combine_df=pd.concat([new_land, new_shore])

In [11]:
combine_df.to_csv('RC_data.csv',index=False,header=True)